### ISSUE TITLE
Need to not have to run it as sudo 

### ISSUE THREAD

**Issue by CleanMachine1** [CleanMachine1/Linux-DNS-Set#2]
@Itai-Nelken You may be able to help me with this, I have been looking into it and I could use something such as

``` 
echo "$data" | sudo tee test.txt

```

How can I silence the echo but still give tee the data it needs

**Comment by Itai-Nelken** [comment]
```bash
echo "$data" | sudo tee test.txt >/dev/null
```

**Comment by CleanMachine1** [comment]
Perfect!

**Comment by CleanMachine1** [comment]
Unless you can figure it out the simpleness of > and >> is way nicer because it clears the file for me and writes new lines

I could possibly fix it by rm and adding the file but that would probably break some permissions..

In the mean time I have added a simple checker for whether the file is run as root or not, and it tells the user to rerun if they have.
